// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RazorPage.Data;

namespace RazorPage.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20210520125351_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("RazorPage.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrutSalary")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Civility")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ConfidentialityPoliticAccepted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DayByMonthDuration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Firstname")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lastname")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MarketingOfferAccepted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MonthDuration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NetSalary")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PriceType")
                        .HasColumnType("TEXT");

                    b.Property<string>("PriceUnit")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResidenceCountry")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkCountry")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
